export const users = [
	{
		id: 1,
		login42: 'test1',
		username: 'Sasha',
		email: 'sasha@prisma.io',
		password: 'sashapass',
		bio: 'Hello guys',
	},
	{
		id: 2,
		login42: 'test2',
		username: 'Florian',
		email: 'florian@prisma.io',
		password: 'flopass',
		bio: 'Coucou',
	},
	{
		id: 3,
		login42: 'test3',
		username: 'Antoine',
		email: 'antoine@prisma.io',
		password: 'antoinepass',
		bio: 'salut',
	},
	{
		id: 4,
		login42: 'test4',
		username: 'Alric',
		email: 'alric@prisma.io',
		password: 'alricpass',
		bio: 'ciao',
	},
	{
		id: 5,
		login42: 'test5',
		username: 'Kay',
		email: 'kay@prisma.io',
		password: 'kaypass',
		bio: 'Hello, good morning',
	},
	{
		id: 6,
		login42: 'test6',
		username: 'Jin',
		email: 'jin@prisma.io',
		password: 'jinpass',
		bio: 'Hello coucou',
	},
	{
		id: 7,
		login42: 'test7',
		username: 'Ting',
		email: 'ting@prisma.io',
		password: 'tingpass',
		bio: 'Heyyyyyyyyy',
	}
]