name: Deploy action

on:
  push:
    branches: [ "prod" ]

# permissions:
#   contents: read

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Python 3.10
  #     uses: actions/setup-python@v3
  #     with:
  #       python-version: "3.10"
  #   - name: Install dependencies
  #     run: |
  #       python -m pip install --upgrade pip
  #       pip install pydo
  #   - name: Reset droplet
  #     env:
  #         DO_TOKEN: ${{ secrets.DO_TOKEN }}
  #     run: |
  #       python .github/rebuild-droplet.py

  deploy:
    runs-on: ubuntu-latest
    # needs: build
    steps:
      - name: Clone and run docker
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: /home/ci/
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          envs: CLONE_DIR
          port: 22
          script: |
            echo "Starting deploy docker ...."
            echo git@github.com:${{github.repository}}.git
            mkdir -p $CLONE_DIR/
            git clone -b master git@github.com:${{github.repository}}.git $CLONE_DIR
            cd $CLONE_DIR
            echo ${{ secrets.FORTYTWO_APP_SECRET }} >> ./build/.env
            echo ${{ secrets.REACT_APP_FORTYTWO_APP_ID }} >> ./build/.env
            echo ${{ secrets.REACT_APP_FORTYTWO_APP_ID }} >> ./build/.env
            echo ${{ env.APP_NAME }} >> ./build/.env
            echo ${{ env.ENV }} >> ./build/.env
            echo ${{ env.REACT_APP_BACKEND_URL }} >> ./build/.env
            echo ${{ env.REACT_APP_FRONTEND_URL }} >> ./build/.env
            make prod

