name: Deploy action

on:
  push:
    branches: [ "prod" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pydo
    - name: Reset droplet
      env:
          DO_TOKEN: ${{ secrets.DO_TOKEN }}
          DO_DROPLET_ID: ${{ secrets.DO_DROPLET_ID }}
          DO_IMAGE: ${{ secrets.DO_IMAGE }}
      run: |
        python .github/rebuild-droplet.py

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Clone and run docker
        uses: appleboy/ssh-action@master
        env:
          CLONE_DIR: /home/ci/
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PWD }}
          envs: CLONE_DIR
          port: 22
          script: |
            echo "Starting deploy docker ...."
            git clone -b prod git@github.com:${{github.repository}}.git $CLONE_DIR
            cd $CLONE_DIR

            # GitHub vars
            echo "ENV=${{ vars.ENV }}" > ./.env
            echo "APP_NAME=${{ vars.APP_NAME }}" >> ./srcs/.env
            echo "REACT_APP_FRONTEND_URL=${{ vars.REACT_APP_FRONTEND_URL }}" >> ./.env
            echo "REACT_APP_BACKEND_URL=${{ vars.REACT_APP_BACKEND_URL }}" >> ./.env
            echo "REACT_APP_GITHUB_LINK=${{ vars.REACT_APP_GITHUB_LINK }}" >> ./.env

            # GitHub secrets
            echo "REACT_APP_FORTYTWO_APP_ID=${{ secrets.REACT_APP_FORTYTWO_APP_ID }}" >> ./.env
            echo "FORTYTWO_APP_SECRET=${{ secrets.FORTYTWO_APP_SECRET }}" >> ./.env
            echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> ./.env
            echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> ./.env
            echo "POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }}" >> ./.env
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> ./.env
            echo "POSTGRES_NAME=${{ secrets.POSTGRES_NAME }}" >> ./.env
            echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> ./.env
            echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> ./.env

            # Let's Encrypt
            echo "${{ secrets.FULLCHAIN }}" > ./srcs/proxy/cert/fullchain.pem
            echo "${{ secrets.PRIVKEY }}" > ./srcs/proxy/cert/privkey.pem

            # Make
            make re

